### ISSUE TITLE
Add a CI/CD workflow

### ISSUE THREAD

**Issue by aaronsteers** [MeltanoLabs/tap-athena#5]
Related MR also opened on the SDK as quickstart for other projects.

Template created there in https://gitlab.com/meltano/sdk/-/merge_requests/202:

```
### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test {{cookiecutter.tap_id}}

on: [push]

jobs:
  linting:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        # Only lint using the primary version used for dev
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
    - name: Install dependencies
      run: |
        poetry install
    - name: Check formatting with black
      run: |
        poetry run black --check .
    - name: Check typing annotations with mypy
      run: |
        poetry run mypy . --ignore-missing-imports

  pytest:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --capture=no
```
